
-- TEST HISTORY & ASSESSMENT STORAGE
-- This table stores every structured report generated by the AI
create table if not exists public.test_history (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  test_type text not null, -- e.g., 'PPDT', 'TAT', 'Interview', 'WAT'
  score numeric default 0,
  result_data jsonb not null, -- Stores the full structured AI response
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.test_history enable row level security;

-- Policies: Users can only see their own history
create policy "Users can view own history" 
on public.test_history for select 
using (auth.uid() = user_id);

-- Policies: System/Admin can insert results
create policy "Users can insert own results" 
on public.test_history for insert 
with check (auth.uid() = user_id);

-- Policies: Admin can view all (for human-in-the-loop review)
create policy "Admins can view all history" 
on public.test_history for select 
using (
  auth.jwt() ->> 'email' IN ('rajveerrawat947@gmail.com', 'admin@ssbprep.online')
);

-- Indexing for performance
create index if not exists idx_test_history_user_id on public.test_history(user_id);
create index if not exists idx_test_history_created_at on public.test_history(created_at desc);
